#### Уровень 0
Придумайте матрицы, которые обладают следующими свойствами:

a) диагональная, ортогональная, но не единичная(!):

b) верхнетреугольная, ортогональная:

c) нижнетреугольная, ортогональная:

d) матрица, у которой определитель = 1, и все элементы не равны 0:

P.S. Во всех пунктах ответом должна быть ненулевая матрица размерности не менее 2!

Найдите собственные значения и собственные вектора матриц:
m = np.array([[2, 2],
[1, 3]])
print(m)

In [1]:
import numpy as np

In [24]:
a = np.array([[-1,0,0],[0,-1,0], [0,0,-1]])
np.dot(a,a.transpose())

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [43]:
b = np.array([[-1,0,0],[0,1,0], [0,0,-1]])
np.dot(b,b.transpose())

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [46]:
c = b.transpose()
np.dot(c, c.transpose())

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [55]:
d = np.array([[7.,9.],[3.,4.]])
np.linalg.det(d)

1.0000000000000013

In [59]:
m = np.array([[2, 2], [1, 3]]) 
np.linalg.eig(m)

(array([1., 4.]),
 array([[-0.89442719, -0.70710678],
        [ 0.4472136 , -0.70710678]]))