### Уровень 0:
Создайте матрицу 3 на 3, заполненную числами от 1 до 9
Прибавьте к ней матрицу с единицами на диагонали
Умножьте полученную матрицу на вектор (1, 2, 3)
Посчитайте обратную матрицу к полученной матрице

In [7]:
import numpy as np

In [11]:
matrix = np.array([np.random.randint(1.,9.,3),np.random.randint(1.,10.,3),np.random.randint(1.,10.,3)])
matrix

array([[8, 5, 5],
       [2, 2, 7],
       [1, 3, 3]])

In [12]:
one = np.eye(3)
one

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
result = matrix + one
result

array([[9., 5., 5.],
       [2., 3., 7.],
       [1., 3., 4.]])

In [28]:
np.dot(result, np.array([1.,2.,3.]))

array([34., 29., 19.])

In [29]:
result_inv = np.linalg.inv(result)
result_inv

array([[ 0.12676056,  0.07042254, -0.28169014],
       [ 0.01408451, -0.43661972,  0.74647887],
       [-0.04225352,  0.30985915, -0.23943662]])

In [31]:
np.dot(result_inv, result)

array([[ 1.00000000e+00,  5.55111512e-17,  0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00, -4.44089210e-16],
       [-5.55111512e-17,  0.00000000e+00,  1.00000000e+00]])